import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import React, {useContext} from 'react'
import ReactMarkdown from 'react-markdown'
import rehypeExternalLinks from 'rehype-external-links'
import beginnersGuideMd from '../resources/beginnersGuide.md?raw'
import beginnersGuideRedditIntroMd from '../resources/beginnersGuideRedditIntro.md?raw'
import CardHeader from '@mui/material/CardHeader/index.d.ts'
import CopyMarkdownButton from '../info/CopyMarkdownButton.jsx'
import DBContext from '../app/DBContext.jsx'

function BeginnersGuide() {

    const {adminRole} = useContext(DBContext)

    const doNotEdit = '[//]: # (PLEASE DO NOT EDIT THIS FILE DIRECTLY, CHANGES MAY BE LOST)\n' +
        '[//]: # (IT IS GENERATED AUTOMATICALLY FROM THE LATEST CONTENT BY LPUBELTS.COM)\n' +
        '[//]: # (PLEASE CONTACT ANYONE ON THE TEAM AND WE WILL MAKE CHANGES FOR YOU)\n\n'

    return (
        <Card style={{
            maxWidth: 800,
            marginLeft: 'auto',
            marginRight: 'auto',
            marginTop: 16,
            marginBottom: 16
        }}>
            {adminRole &&
                <CardHeader action={
                    <CopyMarkdownButton
                        content={doNotEdit + String(beginnersGuideRedditIntroMd) + String(beginnersGuideMd)}
                        filname='beginnersGuide'
                    />
                }/>
            }
            <CardContent>
                <h1>
                    Beginner&#39;s Guide to Lockpicks and Friends
                </h1>
                <ReactMarkdown rehypePlugins={[[rehypeExternalLinks, {target: '_blank'}]]}>
                    {String(beginnersGuideMd)}
                </ReactMarkdown>
            </CardContent>
        </Card>
    )
}

export default BeginnersGuide
