import defaultEntries from '../src/data/data.json' with {type:'json'}
import searchEntriesForText from '../src/filters/searchEntriesForText.js'
import entryName from '../src/entries/entryName.js'
import removeAccents from 'remove-accents'
import {json2csv} from 'json-2-csv'
const mappedEntries = defaultEntries.map(addFuzzy)

const locks = [
    'ABUS 45 laminated padlock',
    'Any Acrylic Padlock',
    'Any lock with any tool',
    'Alpha 1000 1000 up to 35mm, 2 or 3 pins',
    'Any China Padlock (granite look)',
    'Any Cutaway Lock',
    'Brüder Mannesmann <50mm padlock <5 pins',
    'Generic/Unknown 1 or 2 Lever Cabinet lock',
    'Master Lock #1',
    'Master Lock #2 laminated brass',
    'Master Lock #3',
    'Master Lock #4 laminated brass',
    'Master Lock #5',
    'Master Lock #6 laminated brass',
    'Master Lock #7',
    'Master Lock #8 laminated brass',
    'Timpson Special Brass Padlock',
    'Tri-Nine Padlock',
    'ABUS 45/30, 45/35 4 pin',
    'ABUS 55/30',
    'ABUS 64Ti Titalium 30mm or smaller (<5 pins)',
    'ABUS 65/35 35mm or smaller',
    'ABUS 72/40 Unguttable "Love Lock"',
    'ABUS 84/35',
    'ABUS  85 4 pins (30mm and under)',
    'ABUS Nautic T84MB/40, 84/35 40mm or larger',
    'ABUS T65AL MyLock',
    'ACE Laminated padlock 40mm or larger',
    'Alpha 1000 40-45mm, 4 pins, spools',
    'American Lock 5200 bump stop model: all standards + 1 anti-bump pin',
    'ARFE padlock',
    'ASSA 8450/10450 Cam Lock Same as H5/H7 but without tapering',
    'BASI ST/CO',
    'Befa',
    'Börkey',
    'Braslock',
    'Brinks 164 Pin Tumbler Padlock',
    'Brinks Brass Padlocks',
    'Brinks laminated padlock with or without weatherproof',
    'Brinks R60, R70, R80 Disk lock',
    'Brüder Mannesmann 50mm or larger padlock 5 pins',
    'BSS',
    'Burg Wächter "Alutitan" 770 40',
    'Burg Wächter "C-Line" 222 40 / C30',
    'Burg Wächter "Look" 402 40',
    'Burg Wächter "SecuLock" 405 40',
    'Burg Wächter "Yacht" 460 Ni 40',
    'Citadel Padlock',
    'Classic  5 pins, inverted Yale keyway',
    'Defiant Interior 5 pins, 1 spool',
    'Dulimex DX',
    'Eagle 37110',
    'Egret 5-pin padlock',
    'ERA Mortice 2 lever',
    'Esco',
    'Faithfull',
    'FF',
    'Generic/Unknown 3 Lever Cabinet lock',
    'Generic/Unknown 3 Lever Mortice lock',
    'GEZE Standard',
    'GLK 60G50 50mm padlock',
    'GLK G10',
    'Guri',
    'Heracles Y7',
    'IFAM Start 50 Padlock',
    'ISEO, Gera F3, 5900',
    'Koala',
    'Locinox Standard 4 pins',
    'Lockwood 412/312',
    'MAKO 227',
    'Master Lock 5UP Laminated Padlock W/ Rekey',
    'Master Lock 130, 9130EURD',
    'Master Lock 140,141, 9140EURD',
    'Master Lock 930',
    'Master Lock DG',
    'Master Lock Magnum',
    'Master Lock V-line 4140',
    'Metal',
    'Multi XL',
    'Phillips 112 Padlock 4 pins',
    'Santos',
    'Schlage Everest',
    'Schlage Original Commercial/Residential',
    'Smith and Locke 1634G Non-British Standard 3 lever',
    'Squire 440 4 lever, pin key',
    'Squire 660 4 lever',
    'Squire Defiant 5 lever',
    'Stabilit',
    'Takigen C-187-1 4 pins, 2 rows',
    'Thirard Eco',
    'Wolfdog padlock',
    'ABUS 5/45 Silver Rock',
    'ABUS 41  5 Pins (40mm or larger)',
    'ABUS 45/50 brass body',
    'ABUS 55/40 40mm or larger',
    'ABUS 60/50',
    'ABUS 64Ti Titalium , MyLock T65AL, 70AL45 40mm or larger (5+ pins)',
    'ABUS 65/40',
    'ABUS 82/63 Monoblock, spools with one standard driver',
    'ABUS 85 5 pins (40mm and larger)',
    'ABUS Buffo (Ecoline)',
    'ABUS C51',
    'ABUS C83 Old pinning',
    'ABUS Diskus normal pin-tumbler, not dimple',
    'ABUS E50, Citadel N',
    'ABUS Monobloc',
    'ABUS Pfaffenhain Standard 5 pin spools only (older pinning)',
    'ABUS 54TI/50 Titalium',
    'ABUS Ti12, Ti14 Titalium / E100',
    'ABUS W14 5 pin spools only',
    'ACE Tubular',
    'Alpha 1000 1000 50mm or larger, 5 pins, spools',
    'An Jia Bao / HPP / Ming Gao disc detainer padlock 5-6 disc generic disc detainer padlock with same style keybow',
    'ASSA Cam Lock H5/H7',
    'BAB DESS5',
    'BASI AS',
    'BASI CO',
    'BASI ST',
    'BASI V50',
    'BKS Helius',
    'Brinks House Key',
    'Burg Wächter Boccia',
    'Burg Wächter Karat 4 pins (30mm)',
    'Burg Wächter Profil 116 4 pins (30mm)',
    'CES KB',
    'CES PS5',
    'CES WM 5',
    'Cisa 220/50',
    'Cocraft 6-Pin Padlock non-guttable version',
    'Corbin Arco Cromato',
    'Commando Peacemaker',
    'Defiant Exterior 5 pins, 3 spools',
    'Eurospec (E*S) Easi-T British Standard - 5 lever, Brass key, 2004+',
    'Eclipse (any model) British Standard - 5 lever, 2007+',
    'FAB 100',
    'FAB Control',
    'Fanal 5-pin padlock',
    'Federal Super F50/F60 5 pins',
    'FCV',
    'FUG',
    'FXL',
    'Garrison 40mm Brass Padlock',
    'Heracles 5G',
    'IKON DS',
    'ISEO, Gera F5, 5600 4 and 5 pin',
    'GTV Padlock',
    'Kasp 160 series Diskus',
    'LOB Standard',
    'Lockwood 110/40',
    'Lockwood 120/30',
    'Mailboss "12" wafer mailbox camlock',
    'Master Lock 150 / 9150EURD / 160',
    'Master Lock 1921D "100 Anniversary" Padlock 4 pins',
    'Master Lock V-line 4150',
    'Master Lock 532',
    'Master Lock 570,575,576',
    'Medeco Keymark',
    'Phillips 113 Padlock 5 pins',
    'Reliabilt LOTO 6 pins',
    'Schlage Everest',
    'Schlage Original F-series KiK with collapsible bible',
    'SIB',
    'SMB',
    'SOLXD',
    'Starlet',
    'TESA TE-5',
    'Trelock Euro Cylinder',
    'Trimas',
    'Urbis',
    'Wilka standard profile 5 pin',
    'Wilka 1400 5 pin',
    'Winkhaus AZ',
    'Winkhaus VS 5 5 pin',
    'Yale 5 lever sashlock 5 Lever',
    'Yale Y110 all padlock formats, 40mm or larger',
    'Yale 112 Disc Detainer',
    'Yale Y120 all padlock formats',
    'Yale 122/50',
    'Yale 125/40',
    'Yale Mortise',
]

const entryMatches = locks.map((lock) => {
    const matches = searchEntriesForText(lock, mappedEntries)
    return matches.length
    ? {matchId: matches[0].id, ranking: matches[0].belt, matchName: `${entryName(matches[0])} ${matches[0].version ? matches[0].version : ''}`}
    : {matchId: '', ranking: '', matchName: 'no match'}
})


console.log(json2csv(entryMatches, {delimiter: {field: '|||'}}))


function addFuzzy(entry) {
    const fuzzy = removeAccents(
        [entryName(entry, 'long')]
            .concat([
                entry.searchKeywords,
                entry.notes,
                entry.version,
                //entry.belt
            ])
            .join(',')
    )
    return {...entry, fuzzy}
}