import defaultEntries from '../src/data/data.json' with {type:'json'}
import searchEntriesForText from '../src/filters/searchEntriesForText.js'
import entryName from '../src/entries/entryName.js'
import removeAccents from 'remove-accents'
import {json2csv} from 'json-2-csv'
const mappedEntries = defaultEntries.map(addFuzzy)

const locks = [
    'Abloy Disklock ',
    'Abloy High Profile ',
    'ABUS Plus with butterfly discs',
    'ABUS EC700,EC800 ',
    'ALPHA FB ≥12 pins',
    'MIWA,Anker (MIWA/Ankerslot) 3800 ',
    'ASSA,Ruko 600,600 6 pin, with gin spools and matched countermilling',
    'ASSA,Ruko 700 with gin drivers and matched sleeve',
    'ASSA 700 7 pin, with gin/tree pins and matching countermilling in 4+ chambers, < 2 tree pins',
    'ASSA,Ruko,Trioving dp2,dp2400/dp10,System 10 6 pin 4 slider',
    'ASSA Twin Exclusive LFIC, Twin 6000 LFIC Red if picked to only one shear line',
    'Banham m2002 ',
    'Australian Lock Co. BiLock 12 sliders, 3-4 mastered',
    'BKS Janus < 13 pins',
    'Bramah bp17 ',
    'Chubb, Union 110 (3g110) 5 lever',
    'CISM Atlas ',
    'Clavis T-20 15-19 pins',
    'DOM / Inn ix Saturn / Key Smart ',
    'DOM / Dorma RS 8 ',
    'Elzett M (aka Elzett Magnet)',
    'Corbin Russwin Emhart 6 pins **',
    'EVVA 3KS/3KS+/4KS without false gates or 1-3 mastered sliders',
    'EVVA Dual >4 mastered elements',
    'EVVA ICS >2 mastered elements',
    'FAB NZS3 ',
    'Fichet 450,484 w/ false gates, 2-3 mastered levers',
    'Fontaine Dynaxis ',
    'FTH Thirard Pacific ',
    'GOAL v18,GP <14 pins',
    'GOAL Z ≥2 standard drivers',
    'Hori Trident spools',
    'IKON tk5 sperwellenprofil with serrated fingerpins',
    'IKON SK6 Sperrwelle 4 serrated finger pins, non-chamfered sidebar',
    'IKON Verso ',
    'Kaba 14 13+ pins',
    'Kaba,MIWA 20/Star,JN 4 directions, < 15 pins',
    'Kaba Ace ≥13 pins',
    'Kaba,Kaba experT,Quattro <15 pins',
    'Kaba Gemini ≥13 pins',
    'Kaba Gemini pluS ≥14 pins',
    'Kaba Penta / Penta Cross <15 pins',
    'Kaba Star 5+ directions, <16 pins',
    'Keso 6000 FP2 / 8000 Omega^2 ≥13 pins',
    'Kromer Novum ',
    'Locksys Codkey L52 ',
    'Maglok  ',
    'Mauer Crypto ',
    'Mauer Praetor B (70079) 11 lever',
    'Medeco M4 6 pin stacks, 4 side pins',
    'MIWA E6,83EC ',
    'MIWA LS7 ',
    'MIWA PR <7 unmastered levers',
    'MIWA,Tostem PS,DN 7-8 unmastered levers',
    'MIWA SR ',
    'MIWA U9,UR <8 unmastered levers, barred false gates (old shallow false gates  equals a belt below)',
    'Mottura 52 7 lever',
    'Mottura Champions C55, CP6 ',
    'Mul-T-Lock  MT5+ 4 top stacks, 4 sliders (short KIK version)',
    'Picard,Heracles Vigie,Pericles euro profile version',
    'Robur 2391 Safe Deposit Lock barrels 3+ chambers with matched milling',
    'Robur 2391 Safe Deposit Lock gins 3+ chambers with matched milling',
    'Rosengrens 32A,32A8 thin round center posts, few or no false gates',
    'S&G 4440 series ',
    'Schlage Everest 29 SL Primus XP ',
    'Sémag Euromag ',
    'Tann  10 lever',
    'Tann, Chubb, WLN Detector,Detector from 1950s ',
    'U-Shin Showa NX ≥13 pins',
    'Vachette AxiTec ',
    'Vachette Radial,Radial NT,Radial NT+,Radial S,Radial Si ≥13 pins',
    'Winkhaus X-Tra 9-13 pins',
    'Xylock  ',
    'Yanai R2200M <14 Pins',
    'BB Level 1  ',
    'Abloy Sentry ',
    'Alpha Frost 16 Pins',
    'ASSA 700 gin/tree pins and matching countermilling in 4+ chambers, ≥ 2 tree pins',
    'ASSA Twin Exclusive,Twin 6000 6 barrel drivers, 5 side pins',
    'ASSA Twin Exclusive LFIC, Twin 6000 LFIC Picked to both shear lines in single take',
    'ASSA Twin Maximum,Twin Pro,Twin v10,Twin 2,Twin Global barrel driver, 6 stacks with 5 side pins',
    'ASSA Twin Exclusive 5700 (Baltic) 6 pin with 5 side pins with 4 possible heights each',
    'Australian Lock Co. BiLock 12 sliders, 1-2 mastered',
    'Bowley Door Lock ',
    'BKS Janus 13 or more pins',
    'Chubb "Definitive" Standard mortise, 5 lever',
    'Clavis Q-18 ',
    'DOM Diamant ',
    'DOM ix Twinstar ',
    'Corbin Russwin Emhart 2+ mastered chambers **',
    'EVVA 3KS,3KS+ with false gates and no mastered sliders',
    'EVVA Dual 1-4 mastered elements',
    'EVVA ICS ',
    'Fichet 450,484 w/ false gates, 1 mastered lever',
    'Fichet F3D indoor cylinder',
    'Fichet-Bauche M2B,M3B ',
    'GOAL,GOAL V18,GP 14-16 pins',
    'GOAL Z <2 standard drivers',
    'IKON WSW 5 sliders',
    'JPM,Ruko Surf,Combi Plus 6 pin with 5 side pins with 3 possible heights each',
    'Kaba,MIWA 20/Star,JN 4 directions, 15+ pins',
    'Kaba Quattro,experT 15-20 pins',
    'KABA Matrix 16 pins - fully pinned',
    'Kaba Star 5 or more rows, 16-20 pins',
    'Kaba Penta / Penta Cross 15-20 pins',
    'Kaba Titan, Titancombi, Aura ',
    'Lockman Megacross with pyramid drivers (SP?)',
    'MIWA LB ',
    'MIWA LS10 ',
    'MIWA PR 7-8 unmastered elements',
    'MIWA U9,UR 8 unmastered elements, barred false gates (old shallow false gates  equals a belt below)',
    'MIWA WR ',
    'Mottura Champions C43,C44,C48,C9P (C43 Plus) ',
    'Mul-T-Lock,Lockwood,IKON MT5+/800,MT5,R10 not mastered',
    'Rosengrens 32A81S,32C81P triangular central posts and many false gates',
    'Ruko,Ruko,FAB Combi 2,Garant 10,Variant 6 pin with 5 finger pins',
    'Sargent Keso ',
    'Tokoz Pro ',
    'UrbanAlps Stealth Key SK1 ',
    'Vachette Radial,Radial NT,Radial NT+,Radial S,Radial Si 18+ pins',
    'Winkhaus X-Tra ≥13 pins',
    'Yanai R2200M 14-16 Pins',
    'BB Level 2  ',
    'Abloy Disklock Pro,Novel ',
    'Abloy Easy ',
    'Abloy Exec ',
    'Abloy Sento ',
    'ASSA,Ruko Twin Combi,Garant with gin drivers',
    'ASSA,TrioVing Twin Combi/Triton/Neptun 4900,Twin Control 6 pin with 5 finger pins',
    'ASSA Twin v10 gin drivers, 6 stacks with 5 side pins',
    'ASSA Twin 6000 gin drivers, 6 stacks with 5 side pins',
    'Australian Lock Co. BiLock 12 sliders, 0 mastered',
    'Australian Lock Co. BiLock (SCEC approved; formerly: ASIO) 2nd/3rd gen (note: two false gates per pin, staggered rows)',
    'Australian Lock Co. BiLock Exclusive picked to control',
    'Bowley Door Lock ',
    'Clavis F-22 ',
    'Clavis T-20 20 pins',
    'EVVA Dual 0 (zero) mastered elements',
    'EVVA ICS 0 (zero) mastered elements',
    'Fichet 450,484 w/ false gates, 0 mastered levers',
    'GOAL V18,GP ≥17 pins',
    'Hori Trident T-spool drivers',
    'IKON SK6 Sperrwelle Extra Code 6 pin with 5 finger pins',
    'IKON WSW 7 sliders, upgrade of WSW with 5 sliders',
    'Kaba Quattro,experT 21 pins',
    'Kaba Star 5+ rows, 21 or more pins',
    'Kaba Penta / Penta Cross 21 or more pins',
    'MIWA PR 9-10 unmastered elements',
    'MIWA U9,UR 9 unmastered elements, barred false gates (old shallow false gates equals a belt below)',
    'Robur Disc Detainer SDB lock ',
    'WEST 917 ',
    'UrbanAlps Stealth Key SK2 ',
    'Yanai R 2200M 17 or more pins',
    'BB Level 3  ',
    'Abloy Protec ',
    'Abloy Protec2 ',
    'ASSA,TrioVing,Ruko dp4400/dp11,dp,Garant+ 6 pin with 10 sliders',
    'EVVA,IKON MCS gen 1/MCS gen 2,M with up to 5 additional gates for mastering',
    'Fichet 787 no blocker (usually interior)',
    'Fichet-Bauche MPX With anti-pick serrations, must be picked clockwise',
    'GOAL Grand V ',
    'MIWA PR 11 unmastered elements',
    'West 941 ',
    'Fichet-Bauche M2i Must be picked clockwise',
    'CAWI 7113, 7123 Protector ',
    'GSK X24 ',
    'BB Level 4  ',
    'Chubb 6K174 Isolator ',
    'Chubb "Definitive" jewelry box (steel comb leaf spring)',
    'Opnus MMXII ',
    'Opnus Memolis ',
    'BB Level 5  ',
    'Fichet F3D outside cylinder - upgrade of indoor cylinder',
    'Kromer Protector (BP55K) ',
    'Kromer Protector (Non-BP55K) ',
    'NATO Mersey 10 lever, pre-1973',
    'NATO Mersey 14 lever',
    'Western Electric 30B Very similar to 30C, spring mechanism instead of blocker',
    'Western Electric 30C ',
    'Yuema,Forte 750,Enigma ',
    'Chatwood Invincible Single Bitted',
]

const entryMatches = locks.map((lock) => {
    const matches = searchEntriesForText(lock, mappedEntries)
    return matches.length
    ? {matchId: matches[0].id, matchName: `${entryName(matches[0])} ${matches[0].version ? matches[0].version : ''}`}
    : {matchId: '', matchName: 'no match'}
})


console.log(json2csv(entryMatches, {delimiter: {field: '|||'}}))


function addFuzzy(entry) {
    const fuzzy = removeAccents(
        [entryName(entry, 'long')]
            .concat([
                entry.searchKeywords,
                entry.notes,
                entry.version,
                //entry.belt
            ])
            .join(',')
    )
    return {...entry, fuzzy}
}