name: PR Check

on:
  pull_request:

jobs:
  deploy:
    name: PR Check
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build and Deploy
        run: yarn ci-pr
